title: ByteBuffoons-Pages
owner_name: KinetekEnergy
github_username: KinetekEnergy
github_repo: "ByteBuffoons-Pages"
baseurl: "/ByteBuffoons-Pages"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/KinetekEnergy"}
plugins:
- jekyll-remote-theme
future: true
